### ISSUE TITLE
Support Stripe email receipts

### ISSUE THREAD

**Issue by CharbelX** [christophercliff/flatmarket#15]
As described here https://support.stripe.com/questions/email-receipts , Stripe has two ways to manage email receipts:

1. passing in a `receipt_email` with the charge creation request
2. or setting an `email` when creating a customer, and then turning on customer receipts from the email settings in Stripe dashboard 

As shown below (code from hapi-flatmarket/lib/index.js), Flatmarket can handle plans (in which case it uses `stripe.customers.create`) or single charges (in which case it uses `stripe.charges.create`):
![screen shot 2016-04-13 at 13 51 34](https://cloud.githubusercontent.com/assets/18441091/14492354/f2dca0a0-017e-11e6-88c4-6a1e26983d29.png)

The question is: Is it possible to support email receipts by slightly modifying this?
Thanks in advance!

**Comment by CharbelX** [comment]
If I add `receipt_email: 'email'` after `source: req.payload.token,`, it doesn't work.
![screen shot 2016-04-13 at 15 50 56](https://cloud.githubusercontent.com/assets/18441091/14495447/c1c728c6-018f-11e6-92eb-d254942d0906.png)

**Comment by christophercliff** [comment]
Yes it should be possible and it looks like you're on the right track. I don't have time to look into this in the short term.
