### ISSUE TITLE
Having issues getting started

### ISSUE THREAD

**Issue by bdunbar** [christophercliff/flatmarket#19]
Hi,

I've got a static site (S3), want to get up and running with Stripe.

I've got the demo running locally - no problem.

I'm missing something fundamental moving from the demo to a static site and proxy server.  Which pieces go where?

**Comment by bdunbar** [comment]
Thanks - I'll either get some sleep or have some coffee and have a go at this.

**Comment by Xen0phobe** [comment]
I'm going to give this a shot as well. @bdunbar let me know how you fare.

**Comment by bdunbar** [comment]
Created proxy on Heroku 

CORS_ORIGINS = https://spacefore.com/
SCHEMA_URI = https://spacefore.com/flatmarket.json
STRIPE_SECRET_KEY = redacted-value

it crashes on creation, log at https://gist.github.com/bdunbar/8c0ffa6d6d0c8a60dc82bd99fc33d90f

**Comment by christophercliff** [comment]
See https://github.com/christophercliff/flatmarket-server-heroku/issues/1#issuecomment-137108161
