### ISSUE TITLE
HTTPS error?

### ISSUE THREAD

**Issue by ColeTownsend** [christophercliff/flatmarket#40]
Hey Chris, first off thank you a million times for making this. Its quite rad. 

I'm running into what appears to be an SSL error. I did a little research and it seemed like the old SSL token for webpack-dev-server was out of date. Below is the error I get. I would assume the reason I'm not getting the js payload is because of the SSL issue.

![image](https://cloud.githubusercontent.com/assets/987654/21463194/ca4422a8-c933-11e6-8f48-50fb1e24fd3e.png)

**Comment by christophercliff** [comment]
I just tried this with a fresh install and couldn't recreate the error. Couple things you could try:

1. Make sure you're loading the page over HTTPS, e.g. [https://127.0.0.1:8000/](https://127.0.0.1:8000/).
2. You have to manually add an exception in Chrome for the bogus localhost cert. An easy way to check this is to open [https://127.0.0.1:8002/app.js](https://127.0.0.1:8002/app.js) in a new tab. There should be a Chrome UI with a link like "(unsafe) proceed to 127.0.0.1".

If that doesn't work there might be something else going on...

**Comment by ColeTownsend** [comment]
@christophercliff wow, I totally thought I tried that but didn't realize it added an exception. Cheers!
