### ISSUE TITLE
Is the product amount updated?

### ISSUE THREAD

**Issue by davejm** [christophercliff/flatmarket#41]
I want to use this project for potentially one-off products. I understand the whole concept is serverless but is there a way to decrement the product amount after a purchase?
edit: Maybe using firebase.io for product details instead of static hosting?

**Comment by christophercliff** [comment]
No, that's the big limitation of this approach. If you have high-demand low-inventory products you'll probably be better off with a traditional e-commerce backend.

Depending on your use case, you might consider using Flatmarket with [auth and capture](https://support.stripe.com/questions/does-stripe-support-authorize-and-capture) enabled (see [`capture`](https://github.com/christophercliff/flatmarket/tree/master/packages/flatmarket-schema#stripe-object) in the spec). This splits a sale into two steps where the seller must manually accept the payment from the Stripe admin. That way if you receive orders you can't fulfill, you can resolve them with the customer without charging them.
