### ISSUE TITLE
Additional flatmarket-cli options

### ISSUE THREAD

**Issue by johnsgill3** [christophercliff/flatmarket#45]
I'd love to use flatmarket and integrate into an already existing site.

I guess I can copy and paste the HTML from the `build/` directory into my site. However my request is for options to specify the `template` as well as the resulting page name (i.e. not `index.html`).

Existing
```
    -h, --help                     output usage information
    -c, --component [file]         the Component
    -d, --destination [dir]        the build directory
    -D, --dev                      run in dev mode
    -p, --preview                  run in preview mode
    -s, --source [dir]             the source directory
    -S, --stripe-secret-key [key]  the Stripe secret key passed to the local server
    -V, --version                  output the version number
```
New Options:
```
   -t, --template [file]    Template HTML doc
   -o, --output [file]       Resulting HTML page name
```

**Comment by christophercliff** [comment]
Could you please provide some more info:

- What is flatpack?
- How do you intend to use these new CLI options with it?

**Comment by johnsgill3** [comment]
Sorry I meant flatmarket. This is what I get for opening PR late at night.

The new CLI options allow developers to integrate the flatmarket place into existing template designs and a 'store' sub-page instead of having it be the index of the site.

**Comment by christophercliff** [comment]
Thanks for the contribution but I'm not convinced this is the appropriate solution. For now, I'd prefer this be handled on the user side. For renaming you could do something like:

```sh
flatmarket && mv build/index.html build/store.html
```

For custom templates you should take a look at the [theme API](https://github.com/christophercliff/flatmarket#using-themes). If integrating with an existing JavaScript or React app, take a look at the [flatmarket-ui API](https://github.com/christophercliff/flatmarket/tree/master/packages/flatmarket-ui).
