### ISSUE TITLE
Integrating a different static front-end?

### ISSUE THREAD

**Issue by NHQ** [christophercliff/flatmarket#48]
How would one go about this?  If I want to build a totally bespoke site, is there an API schema for server?

Sweet project, btw :+1:

**Comment by christophercliff** [comment]
Thanks. There's a small JavaScript SDK for creating charges once you have the Stripe token: https://github.com/christophercliff/flatmarket/tree/master/packages/flatmarket-client#api-reference

The shape of the POST body is defined here: https://github.com/christophercliff/flatmarket/blob/master/packages/flatmarket-validation/lib/index.js#L4-L19.
