### ISSUE TITLE
How do I get started?

### ISSUE THREAD

**Issue by christophercliff** [christophercliff/flatmarket#5]

**Comment by christophercliff** [comment]
# Getting Started Guide

## Install node.js

Make sure you have node.js installed. Flatmarket currently targets `0.10.x`, but the newer versions may work too. Will migrate to the latest major once they merge with io.js.

If you're using Mac OS X, you probably want [node-v0.10.40.pkg](https://nodejs.org/dist/v0.10.40/).

## Install Git

See the [GitHub docs](https://help.github.com/articles/set-up-git/).

## Clone the example repo

Flatmarket comes with a working example to help you get started. Clone the example repo by running:

```sh
$ git clone git@github.com:christophercliff/flatmarket-example.git
```

## Install the dependencies

node.js comes with a package manager called npm. Use it to install the dependencies:

```sh
$ npm install
```

You may need to use `sudo`.

## Create a flatmarket.json

Create a file `./src/flatmarket.json`. This file must be a valid [Flatmarket schema](https://github.com/christophercliff/flatmarket-schema/blob/master/SPECIFICATION.md).

```json
{
  "info": {
    "name": "Your Store"
  },
  "products": {
    "sku_001": {
      "amount": 1000
    }
  },
  "server": {
    "host": "your-flatmarket-server.herokuapp.com"
  },
  "stripe": {
    "publishableKey": "your_publishable_key"
  }
}
```

Also note that contents of the `./src/` directory will be copied to the `./build/` directory. It should contain any static assets you want to make public.

## Run Flatmarket in development mode

Flatmarket has a special mode for developing locally. You can run this in the background while developing. When you change a file, the changes will be automatically reflected in the browser.

```sh
$ ./node_modules/.bin/flatmarket build \
    --component ./lib/index.jsx \
    --stripe-secret-key your_secret_key \
    --dev
```

Notice the example repo specifies a `index.jsx` component, specified with the `--component` option. You can customize this file any way you like. See the [React docs](http://facebook.github.io/react/docs/getting-started.html) for more information.

## Build in production mode

Once you're satisfied with your changes, run a production build:

```sh
$ ./node_modules/.bin/flatmarket build \
    --component ./lib/index.jsx \
```

This command will generate the website in the `./build/` directory.

## Deploy to a static file server

You can deploy the contents of the `./build/` directory to any web hosting service. GitHub Pages and AWS S3 are popular choices. See the [static web hosting guide](https://json.expert/the-holy-grail-of-static-website-hosting/) for more info.

## Deploy the Flatmarket server

The static website communicates with Stripe through a proxy server, specified in `flatmarket.json`. This is a simple service that's aware of your Stripe secret key. It can run on any VPS with node.js support.

Flatmarket comes with a Heroku-ready server that can be installed for free with just one click. Go to [flatmarket-server-heroku](https://github.com/christophercliff/flatmarket-server-heroku) and click "Deploy to Heroku". Enter the configuration information when prompted and start the service.

**Comment by koobs** [comment]
@christophercliff  Will give this a go then report back. Thanks :]

**Comment by cjliu49** [comment]
thanks @christophercliff any updates on this in 2017? Looks like you moved some things around :) will be trying out flatmarket over the next few days. appreciate your work on this!

**Comment by johnsgill3** [comment]
@christophercliff agree with @cjliu49, looks like some things have moved around and maybe node version dependencies need to be looked at. I was trying on my OSX machine with node -v = `v7.7.1` and it doesn't seem to run very smoothly. Maybe I need to downgrade node?
