### ISSUE TITLE
No app.js is created when running the script.

### ISSUE THREAD

**Issue by almet** [christophercliff/flatmarket#50]
First, thanks for writing this piece of software and making it available to everyone! The idea is great and the implementation seems good. I especially like the idea of separating the client from the server side, which makes it very easy to integrate with already-existing websites.

That being said, I have a hard time making this work: I've checked the sources locally and followed the instructions located in the `README.md` but I fail to generate a `app.js` file. I wonder if this is due to recent changes in how webpack works or if it's due to my setup, but here are some details that might be useful in order to debug this.

After checking-out the source locally, I did a `npm install` and `make reset`. Once everything was installed, I tried to run the demonstration with `make example-dev`. Webpack states that it compiled successfully but when I look in the `build` folder, I don't see the `app.js` file that should be in there.

Here is the result of a `tree build`:
```
build/
├── flatmarket.json
├── images
│   ├── banana.png
│   ├── cherry.png
│   ├── peach.png
│   ├── pineapple.png
│   ├── plum.png
│   └── pomegranate.png
└── index.html
```

As you can see, all static files seems to be present *except* `app.js`. It's probably important to note that:

- before running `make example-dev`, I edited it to change the value of the Stripe secret key;
- The `make example-dev` command doesn't return. It just hangs forever if I don't stop it (with ctrl-c)

I admit that I'm not an expert with this ecosystem, and I would love to have some help / hints as to how to make this work, thanks!

**Comment by christophercliff** [comment]
`make example-dev` starts the dev server and loads your JS from `https://127.0.0.1:8002/app.js`.  Run `make example-prod` to do a complete static build.
