### ISSUE TITLE
Differences in Philosophy and Features 

### ISSUE THREAD

**Issue by Immortalin** [christophercliff/flatmarket#51]
Hello, I just came across a [similar](https://medium.com/@patrickmichelberger/building-a-serverless-e-commerce-app-with-aws-lambda-stripe-and-react-4663e241710b) but more recent [application](https://github.com/patrick-michelberger/serverless-shop) that also uses AWS lambda for e-commerce. They support Stripe relay for handling of goods. What are the main differences between it and flatmarket?

**Comment by christophercliff** [comment]
Flatmarket was designed before Stripe released the Relay API so it uses a static JSON document for managing products. This has some limitations, for example you can't represent dynamic inventory and you must deploy the static website to update product content.

**Comment by Immortalin** [comment]
@christophercliff do you think you can add support for Relay?

**Comment by christophercliff** [comment]
It certainly could be added but it's not something I intend to do in the short term.
